name: barikoi_maps_place_picker
description: A Flutter plugin which provides 'Picking Place' using Barikoi Maps widget.
version: 1.0.0
homepage: https://github.com/fysoul17/google_maps_place_picker

analyzer:
  enable-experiment:
    - non-nullable

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  barikoi_api:
    git:
      url: "git://github.com/barikoi/barikoi_api_dartlib.git"
      ref: "bd9647d78ad9022c213f525a15a6ebcfbf5705be"
#  mapbox_gl:  ^0.11.0
  maplibre_gl:
    git:
      url: https://github.com/m0nac0/flutter-maplibre-gl.git
      ref: 0.15.0

  geolocator: ^8.2.0
  permission_handler: ^9.0.1
  provider: ^6.0.2

  tuple: ^2.0.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
